#!/usr/bin/env python3
import csv
from bom_open import bom_open

csv.register_dialect('pipe',
                     delimiter='|',
                     lineterminator='\n',
                     quoting=csv.QUOTE_NONE)
csv.register_dialect('caret',
                     delimiter='^',
                     lineterminator='\n',
                     quoting=csv.QUOTE_NONE,
                     escapechar='\\')

def firstline(string):
    for i, char in enumerate(string):
        if char in '\r\n':
            return string[:i]

    return string

def csv_stdout(f_in,
               f_out,
               header=False,
               delimiters=None,
               output_dialect=None):
    delimiters = delimiters or '|,\t'
    output_dialect = output_dialect or 'pipe'

    peek = f_in.buffer.peek()
    peek_line = firstline(peek.decode(f_in.encoding))
    dialect_auto = csv.Sniffer().sniff(peek_line, delimiters=delimiters)

    if header: # skip over
        f_in.readline()

    reader = csv.reader(f_in, dialect=dialect_auto)
    writer = csv.writer(f_out, dialect=output_dialect)
    writer.writerows(reader)

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("FILE",
                        nargs='?',
                        default='-',
                        help="file to open, '-' or omit to pipe from stdin")
    parser.add_argument("--header",
                        action="store_true",
                        help="discard first row")
    parser.add_argument("--delimiters",
                        help="input delimiters to search for, default '|,\\t'")
    parser.add_argument("--input-encoding",
                        help="default encoding to use if no Unicode BOM in file, UTF-8 when not specified")
    parser.add_argument("--output-encoding",
                        help="output encoding, UTF-8 when not specified")
    parser.add_argument("--output-errors",
                        default="strict",
                        choices=['strict', 'replace', 'ignore', 'backslashreplace'],
                        help="response when input string can't be encoded to output-encoding.")
    parser.add_argument("--output-dialect",
                        choices=['pipe', 'excel', 'excel-tab', 'unix', 'caret'],
                        help="output csv dialect, pipe delimited when not specified")
    parser.add_argument("--output-newlines",
                        choices=['unix', 'dos'],
                        help="output newline character, same as input when not specified")
    args = parser.parse_args()

    if args.output_newlines == 'unix':
        newline = '\n'
    elif args.output_newlines == 'dos':
        newline = '\r\n'
    else:
        newline = ''

    with bom_open(args.FILE, encoding=args.input_encoding, newline=newline) as f_in, \
         bom_open(None, 'w',
                  encoding=args.output_encoding or 'utf-8',
                  errors=args.output_errors) as f_out:
        csv_stdout(f_in=f_in,
                   f_out=f_out,
                   header=args.header,
                   delimiters=args.delimiters,
                   output_dialect=args.output_dialect)
